/* File generated by perl script: get_System_Time.pl , version: V1.0          */                       
/* All rights reserved by ETAS GmbH, Stuttgart, Germany                       */                          
/*                                                                                                          
################################################################################                          
#                                                                              #                          
#                                                |   ETAS GmbH                 #                          
#                                                |   Stuttgart Feuerbach       #                          
#                                                |   All rights reserved       #                          
#                                                |   Alle Rechte vorbehalten   #                          
#                                                                              #                          
################################################################################                          
*/                                                                                                        
/******************************************************************************/                          
/* Copyright and Legal Disclaimer:                                            */                          
/* This Code example was provided by ETAS GmbH, Stuttgart                    */                          
/*                                                                            */                          
/* ETAS will not be held reliable for any usage of this code,                 */                          
/* this code is provided as example code only, and not tested and released    */                          
/* for production code.                                                       */                          
/* ETAS will not guarantee any functional part of this code in any            */                          
/* environment together with any ETAS tools. ETAS will not guarantee that     */                          
/* this code works together with any future versions of ETAS tools.           */                          
/*                                                                            */                          
/* ETAS will not guarantee that this code is free of rights of third parties. */                          
/*                                                                            */                          
/* You are hereby granted the right to use his code as a example for your own */                          
/* ECU implementation together with ETAS Tools. No licenses are granted by    */                          
/* implication or otherwise under any patents or trademarks of ETAS GmbH.     */                          
/* This software is provided on an "AS IS" basis and without warranty.        */                        
/*                                                                            */                          
/* You are not allowed to give these code to third parties without            */                          
/* the written permission of ETAS GmbH.                                       */                          
/*                                                                            */                          
/* To the maximum extent permitted by applicable law,                         */                          
/* ETAS GmbH DISCLAIMS ALL WARRANTIES WHETHER EXPRESS OR IMPLIED,             */                          
/* INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A           */                          
/* PARTICULAR PURPOSE AND ANY WARRANTY AGAINST INFRINGEMENT WITH REGARD       */                          
/* TO THE SOFTWARE (INCLUDING ANY MODIFIED VERSIONS THEREOF)                  */                          
/* AND ANY ACCOMPANYING WRITTEN MATERIALS.                                    */                          
/*                                                                            */                          
/*                                                                            */                          
/* To the maximum extent permitted by applicable law,                         */                          
/* IN NO EVENT SHALL ETAS BE LIABLE FOR ANY                                   */                          
/* DAMAGES WHATSOEVER (INCLUDING WITHOUT LIMITATION, DAMAGES FOR LOSS OF      */                          
/* BUSINESS PROFITS, BUSINESS INTERRUPTION, LOSS OF BUSINESS INFORMATION,     */                          
/* OR OTHER PECUNIARY LOSS)                                                   */                          
/* ARISING OF THE USE OR INABILITY TO USE THE SOFTWARE.                       */                          
/*                                                                            */                          
/*                                                                            */                          
/* ETAS GmbH assumes no responsibility for the maintenance                    */                          
/* and support of this software                                               */                          
/*                                                                            */                          
/*                                                                            */                          
/*  COPYRIGHT (c) ETAS GmbH 2004-2017                                         */                          
/*  All Rights Reserved                                                       */                          
/******************************************************************************/                          


#ifndef __COMPILE_TIME_C__
#define __COMPILE_TIME_C__
#include "../a_std_type.h"

#include "CompileTime.h"

// Code Check Pattern allocate in DATA region of ETK                                                      
#pragma section all ".ETK_Code_checkMemClass"                                                           
#pragma noclear                                                                                           
const volatile uint32 CODE_CHECK_PATTERN_DATA_DATE = 0x07042025;
const volatile uint32 CODE_CHECK_PATTERN_DATA_TIME = 0x111156FF;
#pragma clear                                                                                             
#pragma section all                                                                                       
                                                                                                          
// Code Check Pattern allocate in ECU Flash                                                               
const volatile uint32 CodeCheckPattern_ECUCode_Date = 0x07042025;
const volatile uint32 CodeCheckPattern_ECUCode_Time = 0x111156FF;
                                                                                                              
#endif //__COMPILE_TIME_C__                                                                                   
